# Generated by Django 5.1.1 on 2024-09-23 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0003_booking_name'),
        ('worker', '0004_alter_services_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='worker.worker'),
        ),
    ]
