# Generated by Django 5.1.1 on 2024-09-22 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='service_pic')),
                ('skills', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=25)),
                ('service_rate', models.CharField(max_length=25)),
                ('phone', models.PositiveBigIntegerField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.worker')),
            ],
        ),
    ]
