# Generated by Django 5.1.1 on 2024-09-25 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_alter_services_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='profile_pic',
            new_name='service_pic',
        ),
    ]
